[#17] Extend tests for data types in config
Booleans and integer values should not be quoted as strings. Doing so causes
aptly to blow up when parsing the config:

    ERROR: error loading config file /etc/aptly.conf: json: cannot unmarshal string into Go value of type int

These test assert the desired behaviour and will be fixed in subsequent
commits before being merged to master.